const recommendations = [
  {
    id: 1,
    name: 'Jonah Wambua',
    image: 'images/jonah.jpeg',
    profession: 'Software Engineer',
    place: 'Naroibi,Kenya',
    comment: 'Riyaz embodies a growth mindset that fuels his continuous quest for improvement and keeping up with the latest industry trends and technologies, and I am highly confident that his coding skills will lead to numerous achievements.',
  },
  {
    id: 2,
    name: 'Joy Phoebe Onyando',
    image: 'images/Joy.jpeg',
    profession: 'Full-stack Developer',
    place: 'Kenya',
    comment: 'Throughout our time working together, Riyaz consistently demonstrated a deep understanding of various platforms, tools and programming languages like Ruby, React, Redux and JavaScript.',
  },
  {
    id: 3,
    name: 'Hamayoun Ali Babur',
    image: 'images/hamayoun.jpeg',
    profession: 'Full-stack Developer',
    place: 'Afghanistan',
    comment: 'Riyaz Ahmad is a highly valuable individual, ensuring smooth progress, meeting deadlines, and upholding top-tier software development standards in every project.',
  },
  {
    id: 4,
    name: 'Samuel Ntow kyere',
    image: 'images/samuel-tikre.jpeg',
    profession: 'Social Entrepreneur | Full-Stack Developer',
    place: 'Ghana',
    comment: 'Riyaz has a rare ability to understand and explain complex technical concepts in a clear and actionable way',
  },
  {
    id: 5,
    name: 'Mudasir Sherwani',
    image: 'images/mudasir.jpeg',
    profession: 'Full-stack Developer',
    place: 'Pakistan',
    comment: 'Riyaz Ahmad is a highly valuable individual, ensuring smooth progress, meeting deadlines, and upholding top-tier software development standards in every project.',
  },
  {
    id: 6,
    name: 'Kwesi Obuobi',
    image: 'images/kwesi.jpeg',
    profession: 'Full-stack Developer',
    place: 'Ghana',
    comment: 'I highly recommend Riyaz as a web developer. His technical prowess, design acumen, and excellent collaboration skills make him a standout choice.',
  },
  {
    id: 7,
    name: 'Rabecca Nabwire',
    image: 'images/Rabecca.jpeg',
    profession: 'Full-stack Developer',
    place: 'Kenya',
    comment: 'Riyaz is one of the most dedicated and enthusiastic people that I have had a chance to meet and interact with. He is very passionate about his work and has the best approach to working together in teams.',
  },
];

export default recommendations;
